"use client";
import {useEffect,useState} from "react";
import {cycleDates,cycleDays,daySchedule,courseColors} from "@/lib/cycle";
function shanghaiDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
export default function CalendarExplorer(){
 const [date,setDate]=useState("");const [wednesday,setWednesday]=useState(false);
 useEffect(()=>{const today=shanghaiDate();setDate(cycleDates.find(d=>d.date>=today)?.date??cycleDates[cycleDates.length-1].date);},[]);
 const entry=cycleDates.find(d=>d.date===date);
 const wed=Boolean(date&&new Date(`${date}T12:00:00Z`).getUTCDay()===3);
 return <><section className="calendar-picker"><label className="field">Choose a date<input type="date" min="2026-08-11" max="2026-10-30" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="calendar-selected" aria-live="polite">{entry?<><span className="mono">DAY {entry.cycleDay} · {entry.parity} · BEIJING TIME</span><h2>{new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`))}</h2><p className="hint">{wed?"Wednesday bell times · no mentoring":"Regular bell times"}</p><ul className="schedule-list">{daySchedule(entry.cycleDay,wed).map(slot=><li className={`course-${slot.color}`} key={slot.period}><span className="mono">{slot.period} · {slot.time}</span><strong>{slot.course}</strong></li>)}</ul></>:<p>{date?"No teaching day is published for this date. The cycle pauses over weekends and the September 25–October 5 break.":"Loading the next school day…"}</p>}</div></section><div className="course-legend" aria-label="Course colors">{Object.entries(courseColors).map(([name,color])=><span className={`course-${color}`} key={name}>{name}</span>)}</div><section className="cycle-grid-section"><div className="landing-section-label"><span className="mono">CYCLE MAP / D1—D8</span><p>Course rotation</p></div><fieldset className="inquiry-start"><legend>Show bell times</legend><button className="button secondary" type="button" aria-pressed={!wednesday} onClick={()=>setWednesday(false)}>Mon / Tue / Thu / Fri</button><button className="button secondary" type="button" aria-pressed={wednesday} onClick={()=>setWednesday(true)}>Wednesday</button></fieldset><div className="cycle-grid">{cycleDays.map(day=><article className="cycle-card" key={day.day}><div><strong>D{day.day}</strong><span>{day.parity}</span></div><ul className="schedule-list">{daySchedule(day.day,wednesday).map(slot=><li className={`course-${slot.color}`} key={slot.period}><span className="mono">{slot.period} · {slot.time}</span><strong>{slot.course}</strong></li>)}</ul></article>)}</div></section></>;
}
