import type { LiteraryReading } from "./literary-reading";

export const bayAtNiceExample: LiteraryReading = {
  title: "The Bay at Nice — David Hare",
  author: "DAVID HARE",
  question: "How does the playwright present the changing relationship between the two characters in this extract?",
  questionCredit: "Supplied guiding question",
  context: "Sophia has decided to tell her mother, Valentina, that she is leaving her husband, Grigor. Read the spoken words and stage directions together.",
  sources: [{ label: "Original supplied page", url: "/examples/bay-at-nice-extract.pdf" }],
  credit: "David Hare, The Bay at Nice. Wording and punctuation follow the supplied extract; speaker labels and stage directions are reformatted for screen reading. The original page preserves the supplied layout. Rights remain with their respective holders. Commentary, practice and models are original teaching material, not an official marked response.",
  passages: [
    { title: "Setting the terms", paragraphs: [
      "**VALENTINA:** I have heard of your behaviour with Grigor.",
      "**SOPHIA:** Mother, I don’t want to speak about it now.",
      "**VALENTINA:** Why?",
      "**SOPHIA:** You will learn in a moment. Soon I shall talk to you.",
      "**VALENTINA:** When?",
      "**SOPHIA:** When I have your whole attention.",
      "**VALENTINA:** Are you choosing your moment?",
      "**SOPHIA:** No.",
      "**VALENTINA:** It sums you up. You think everything is a matter of mood.",
      "**SOPHIA:** I know you better than that.",
      "**VALENTINA:** You think attitudes are all to do with whim. You understand nothing. Attitudes are all to do with character.",
    ] },
    { title: "Equality and the offered embrace", paragraphs: [
      "**SOPHIA:** Please don’t lecture me. *(She is turning red with the effort of having to say this.)* If we are to speak we must speak as equals.",
      "*(VALENTINA is looking across at her with sudden kindness and love.)*",
      "**VALENTINA:** Little Sophia, you’ve used up all your courage already. Come here and tell me what’s going on.",
      "*(SOPHIA, trembling, doesn’t move as VALENTINA opens her arms to her.)*",
      "**SOPHIA:** No, I won’t come. I mustn’t. I’m determined to be strong with you.",
    ] },
    { title: "The speech and the silence", paragraphs: [
      "**VALENTINA:** You’ve come to make a speech?",
      "**SOPHIA:** Well, yes.",
      "**VALENTINA:** Well, make it.",
      "**SOPHIA:** What, now?",
      "**VALENTINA:** Yes.",
      "*(There is an agonizing pause.)*",
      "**SOPHIA:** No, I can’t.",
      "**VALENTINA:** Why not?",
      "**SOPHIA:** Because I have rehearsed but now I’m frightened. I’ve said these things to no one.",
      "**VALENTINA:** And yet everyone knows.",
      "*(SOPHIA does not move.)*",
    ] },
  ],
  sections: {
    "read-before-deciding": { label: "Read & try an idea", phase: "Orient", passage: null },
    "ask-who-sets-the-terms": { label: "Who sets the terms?", phase: "Analyse", passage: 0 },
    "read-the-cost-of-equality": { label: "The cost of equality", phase: "Analyse", passage: 1 },
    "hold-affection-and-authority-together": { label: "Affection & authority", phase: "Analyse", passage: 1 },
    "follow-the-speech-that-does-not-happen": { label: "The failed speech", phase: "Analyse", passage: 2 },
    "read-the-final-stillness": { label: "Final stillness", phase: "Analyse", passage: 2 },
    "build-an-analytical-response": { label: "Build a response", phase: "Write", passage: null },
    "practice-and-transfer": { label: "Practice & transfer", phase: "Write", passage: null },
  },
  firstReading: {
    prompt: "Where does Sophia gain or lose control of this exchange? Connect two moments and identify one detail that complicates your reading of her mother.",
    model: "Sophia sets a condition when she demands to speak as an equal and maintains a boundary by refusing the embrace. Later, her mother tells her to make the speech, and Sophia cannot begin. The exchange suggests how difficult independence is to sustain, even though Valentina’s kindness and love prevent us from treating the encounter as hostility alone.",
    complication: "Sophia’s stillness first accompanies a deliberate refusal and later follows an admission of fear. A similar visible action can acquire a different force as the exchange develops; the ending does not settle all of its possibilities.",
  },
  fields: [
    { key: "contrast", label: "Your revised reading of the relationship", hint: "Trace a change in authority or closeness. What has changed since your first reading?" },
    { key: "evidence", label: "Connected evidence and a complication", hint: "Connect a speech, a response and a stage direction. Include a detail that tests your claim." },
    { key: "analysis", label: "Your analytical paragraph", hint: "Explain how the exchange develops the relationship. Separate written directions from possible performance choices." },
  ],
  checks: [
    "Have I traced a change rather than assigned each character one fixed trait?",
    "Have I connected dialogue with a response or stage direction?",
    "Does my reading account for the explicit kindness and love?",
    "Have I explained what this particular pause delays?",
    "Have I distinguished refusal from inability and evidence from imagined staging?",
    "Have I supported my reading of the ending without inventing a resolution?",
  ],
  filename: "bay-at-nice-notes",
};
