export const passageBooks = [
  [1342, "Pride and Prejudice", "Jane Austen"],
  [158, "Emma", "Jane Austen"],
  [161, "Sense and Sensibility", "Jane Austen"],
  [105, "Persuasion", "Jane Austen"],
  [1260, "Jane Eyre", "Charlotte Brontë"],
  [768, "Wuthering Heights", "Emily Brontë"],
  [1400, "Great Expectations", "Charles Dickens"],
  [98, "A Tale of Two Cities", "Charles Dickens"],
  [2701, "Moby-Dick", "Herman Melville"],
  [74, "The Adventures of Tom Sawyer", "Mark Twain"],
  [76, "The Adventures of Huckleberry Finn", "Mark Twain"],
  [11, "Alice's Adventures in Wonderland", "Lewis Carroll"],
  [1524, "Hamlet", "William Shakespeare"],
  [1533, "Macbeth", "William Shakespeare"],
  [1513, "Romeo and Juliet", "William Shakespeare"],
  [844, "The Importance of Being Earnest", "Oscar Wilde"],
  [174, "The Picture of Dorian Gray", "Oscar Wilde"],
  [84, "Frankenstein", "Mary Shelley"],
  [345, "Dracula", "Bram Stoker"],
  [42, "The Strange Case of Dr Jekyll and Mr Hyde", "Robert Louis Stevenson"],
  [120, "Treasure Island", "Robert Louis Stevenson"],
  [219, "Heart of Darkness", "Joseph Conrad"],
  [55, "The Wonderful Wizard of Oz", "L. Frank Baum"],
  [829, "Gulliver's Travels", "Jonathan Swift"],
  [33, "The Scarlet Letter", "Nathaniel Hawthorne"],
  [209, "The Turn of the Screw", "Henry James"],
  [160, "The Awakening", "Kate Chopin"],
  [1952, "The Yellow Wallpaper", "Charlotte Perkins Gilman"],
  [4517, "Ethan Frome", "Edith Wharton"],
  [541, "The Age of Innocence", "Edith Wharton"],
  [284, "The House of Mirth", "Edith Wharton"],
  [2600, "War and Peace", "Leo Tolstoy"],
  [1399, "Anna Karenina", "Leo Tolstoy"],
  [2554, "Crime and Punishment", "Fyodor Dostoevsky"],
  [135, "Les Misérables", "Victor Hugo"],
  [1184, "The Count of Monte Cristo", "Alexandre Dumas"],
  [103, "Around the World in Eighty Days", "Jules Verne"],
  [164, "Twenty Thousand Leagues under the Sea", "Jules Verne"],
  [36, "The War of the Worlds", "H. G. Wells"],
  [35, "The Time Machine", "H. G. Wells"],
  [236, "The Jungle Book", "Rudyard Kipling"],
  [215, "The Call of the Wild", "Jack London"],
  [37106, "Little Women", "Louisa May Alcott"],
  [17396, "The Secret Garden", "Frances Hodgson Burnett"],
  [289, "The Wind in the Willows", "Kenneth Grahame"],
  [16, "Peter Pan", "J. M. Barrie"],
  [271, "Black Beauty", "Anna Sewell"],
  [1695, "The Man Who Was Thursday", "G. K. Chesterton"],
  [2413, "Madame Bovary", "Gustave Flaubert"],
  [1727, "The Odyssey", "Homer (Samuel Butler translation)"],
  [6130, "The Iliad", "Homer (Samuel Butler translation)"],
  [2383, "The Canterbury Tales", "Geoffrey Chaucer"],
  [2000, "Don Quixote", "Miguel de Cervantes"],
  [15492, "A Doll's House", "Henrik Ibsen"],
  [2500, "Siddhartha", "Hermann Hesse"],
] as const;

