import {writeFileSync} from "node:fs";
import {readingMethods} from "../lib/reading-methods";
import {toneGroups,transitionGroups} from "../lib/language-banks";
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const style=`body{max-width:1000px;margin:32px auto;padding:0 24px;font:16px/1.5 Arial,sans-serif;color:#25282b;background:#f5f5f3}h1{font:36px Georgia,serif}header{border-top:8px solid #25282b}small{font-family:monospace}table{width:100%;border-collapse:collapse}th,td{border:1px solid #9a9e95;padding:14px;vertical-align:top;text-align:left}th{background:#edf2cf}td:first-child{width:34%;background:#eee9dc}td:last-child{min-width:200px}tr{break-inside:avoid}p{margin:8px 0 18px}a{color:inherit;text-underline-offset:3px}.note{font-size:13px}.writing{min-height:90px}footer{margin-top:24px;border-top:1px solid #999}@media print{body{margin:0;padding:0;background:white;font-size:11pt}h1{font-size:24pt}thead{display:table-header-group}.writing{min-height:85px}a{overflow-wrap:anywhere}@page{size:A4;margin:15mm}}`;
function document(title:string,body:string){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>${style}</style></head><body><header><small>MR RINKA / SKILLS &amp; METHODS</small><h1>${escape(title)}</h1></header>${body}<footer><small>MRRINKA.COM / READ · WRITE · THINK</small></footer></body></html>`;}
for(const [key,method] of Object.entries(readingMethods)){
 writeFileSync(`public/downloads/${key}-grid.html`,document(`${method.title} reading grid`,`<p>Text: ______________________________________ Author: ____________________</p><p class="note">Use this to collect observations, then select what supports your interpretation. You do not need one paragraph per box. Print the grid or type into the notes cells, then use Print → Save as PDF to keep your typed notes. Reloading does not save edits.</p><table><thead><tr><th>Reading move</th><th>Evidence and thinking</th></tr></thead><tbody>${method.steps.map(s=>`<tr><td><strong>${escape(s.title)}</strong><p class="note">${escape(s.prompt)}</p></td><td><div class="writing" contenteditable="true" role="textbox" aria-label="${escape(s.title)} notes"></div></td></tr>`).join('')}</tbody></table><p class="note">Worked example: <a href="https://mrrinka.com/resources/reading-methods/${key}">mrrinka.com/resources/reading-methods/${key}</a></p>`));
}
writeFileSync('public/downloads/tone-and-analysis-reference.html',document('Tone, transitions & analytical language',`<p>Name an attitude; support it with evidence. Groups are starting points, not fixed definitions.</p>${toneGroups.map(g=>`<section><h2>${escape(g.title)}</h2><p>${escape(g.words)}</p></section>`).join('')}<h2>Transitions</h2><table><tbody>${transitionGroups.map(([t,w,n])=>`<tr><td>${escape(t)}</td><td>${escape(w)}<p class="note">${escape(n)}</p></td></tr>`).join('')}</tbody></table><h2>Analysis verbs</h2><p>contrasts · juxtaposes · frames · withholds · foregrounds · repeats · implies · evokes · questions · undermines · qualifies · exposes</p><p>Choose the verb that names the writer’s action accurately. Stronger-sounding words are not automatically better.</p><h2>Build a connection</h2><p>Writer → verb → choice and evidence → meaning → explanation.</p><p>“The detail suggests… because…” / “Although… initially suggests…, the later… complicates this by…”</p><p class="note">Further resources: <a href="https://helpfulprofessor.com/analysis-verbs/">Chris Drew, Helpful Professor: analysis verbs</a>; <a href="https://depts.washington.edu/owrc/undergraduate-students/handouts/using-transitions-effectively/">University of Washington OWRC: Using Transitions Effectively</a>.</p>`));
